on:
  pull_request:
    paths:
    - 'data/bedrock**'
  issue_comment:
    types: [created]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

  commentTest:
    runs-on: ubuntu-latest
    outputs:
      ok: ${{ steps.check.outputs.triggered }}
    steps:
      # Check if we were triggered by a comment
      - uses: khan/pull-request-comment-trigger@master
        id: check
        with:
          trigger: '/rerun'
          reaction: thumbsup
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

  test:
    runs-on: ubuntu-latest
    needs: commentTest
    if: needs.commentTest.outputs.ok == 'true' || github.event.action == 'opened'
    steps:
    - uses: actions/checkout@v2
    # - uses: actions-ecosystem/action-regex-match@v2
    - run: npm install
      working-directory: tools/js
    - run: npm build
      working-directory: tools/js
    - name: Comment PR
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: 'Running tests in bedrock-protocol...'
        check_for_duplicate_msg: false  # OPTIONAL 
    - uses: convictional/trigger-workflow-and-wait@v1.3.0
      id: dispatch
      with:
        owner: extremeheat
        repo: bedrock-protocol
        waiting_interval: 60
        inputs: '{"via": "minecraft-data", "reason": "PR"}'
        github_token: ${{ secrets.PAT_PASSWORD }}
        propagate_failure: true
        continue-on-error: true
    - name: Comment OK
      if: steps.dispatch.outcome == 'success'
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: '✅ [Passing tests in bedrock-protocol](https://github.com/extremeheat/bedrock-protocol/actions)'
        check_for_duplicate_msg: false
    - name: Comment Fail
      if: steps.dispatch.outcome != 'success'
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: '❌ [Failing tests in bedrock-protocol](https://github.com/extremeheat/bedrock-protocol/actions)'
        check_for_duplicate_msg: false
