name: handle-mcpc-generator
on:
  workflow_dispatch:
    inputs:
      versions:
        description: 'JSON stringified list of known versions in generator (last is expected to be latest)'
        required: true
        default: '["1.21.6"]'
      mergedArtifactURL:
        description: 'Merged artifact download URL'
        required: true
      prNumber:
        description: 'Relevant minecraft-data-generator PR #'
        required: false
      createPr:
        description: 'Whether to create a new PR if none exists'
        required: false
        default: 'false'

jobs:
  update-mcdata:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1
        with:
          node-version: 22.x
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      # - name: Expose GitHub Runtime
      #   uses: crazy-max/ghaction-github-runtime@v3
      - run: cd .github/helper-bot && bun install
      - run: cd tools/js && bun install
      - run: bun add bun && chmod +x node_modules/bun/bin/bun.exe && node_modules/bun/bin/bun.exe handleMcpcGeneratedArtifacts.js
        working-directory: .github/helper-bot
        env:
          TRIGGER_MC_VERSIONS: ${{ github.event.inputs.versions }}
          TRIGGER_PR_NO: ${{ github.event.inputs.prNumber }}
          TRIGGER_ARTIFACT_URL: ${{ github.event.inputs.mergedArtifactURL }}
          GITHUB_TOKEN: ${{ secrets.PAT_PASSWORD }}
          CREATE_PR_IF_NONE: ${{ github.event.inputs.createPr }}
